version: '3'

networks:
  restaurante-network:
volumes:
  restaurante-volume:

services:
  mongodb-restaurante:
    image: "mongo"
    container_name: "mongodb-restaurante"
    ports:
      - "27017:27017"
    networks:
      - restaurante-network
    volumes:
      - restaurante-volume:/db

  app:
    image: 'backend:dev'
    build:
      context: .
    container_name: "backend"
    depends_on:
      - mongodb-restaurante
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb-restaurante:27017/restaurante-teste?authSource=admin
    networks:
      - restaurante-network
    volumes:
      - restaurante-volume:/backend